/****** Object:  Procedure [dbo].[pr_MIPOD_Update]    Committed by VersionSQL https://www.versionsql.com ******/



CREATE PROCEDURE dbo.pr_MIPOD_Update
	@pohId nvarchar (12),
	@pohRev smallint,
	@podId int,
	@dType smallint,
	@dStatus smallint,
	@invoiced smallint,
	@jobId nvarchar (12),
	@locId nvarchar (6),
	@itemId nvarchar (24),
	@ordered numeric (20, 6),
	@received numeric (20, 6),
	@price numeric (20, 6),
	@cost numeric (20, 6),
	@qInvoiced numeric (20, 6),
	@cInvoiced numeric (20, 6),
	@adCost numeric (20, 6),
	@initDueDate nvarchar (8),
	@realDueDate nvarchar (8),
	@promisedDate nvarchar (8),
	@lastRecvDate nvarchar (8),
	@descr nvarchar (60),
	@mfgId nvarchar (12),
	@viCode nvarchar (255),
	@poUOfM nvarchar (20),
	@poXStk numeric (20, 6),
	@acctId nvarchar (45),
	@idDist nvarchar (6),
	@cmt nvarchar (70),
	@taxCode1 nvarchar (12),
	@taxCode2 nvarchar (12),
	@taxCode3 nvarchar (12),
	@taxCode4 nvarchar (12),
	@taxCode5 nvarchar (12),
	@taxClass1 smallint,
	@taxClass2 smallint,
	@taxClass3 smallint,
	@taxClass4 smallint,
	@taxClass5 smallint,
	@taxBase1 numeric (20, 6),
	@taxBase2 numeric (20, 6),
	@taxBase3 numeric (20, 6),
	@taxBase4 numeric (20, 6),
	@taxBase5 numeric (20, 6),
	@taxRate1 numeric (20, 6),
	@taxRate2 numeric (20, 6),
	@taxRate3 numeric (20, 6),
	@taxRate4 numeric (20, 6),
	@taxRate5 numeric (20, 6),
	@taxAmt1 numeric (20, 6),
	@taxAmt2 numeric (20, 6),
	@taxAmt3 numeric (20, 6),
	@taxAmt4 numeric (20, 6),
	@taxAmt5 numeric (20, 6),
	@taxIncl1 smallint,
	@taxIncl2 smallint,
	@taxIncl3 smallint,
	@taxIncl4 smallint,
	@taxIncl5 smallint,
	@rate numeric (20, 6),
	@rateOper smallint,
	@lineNbr smallint,
	@unitWgt numeric (20, 6),
	@addCost numeric (20, 6),
	@mohId nvarchar (15),
	@momdId int,
	@fldXml text,
	@pohIdOrig nvarchar (12),
	@pohRevOrig smallint,
	@podIdOrig int,
	@TSCol rowversion output
AS
UPDATE MIPOD
SET 	[pohId] = @pohId,
	[pohRev] = @pohRev,
	[podId] = @podId,
	[dType] = @dType,
	[dStatus] = @dStatus,
	[invoiced] = @invoiced,
	[jobId] = @jobId,
	[locId] = @locId,
	[itemId] = @itemId,
	[ordered] = @ordered,
	[received] = @received,
	[price] = @price,
	[cost] = @cost,
	[qInvoiced] = @qInvoiced,
	[cInvoiced] = @cInvoiced,
	[adCost] = @adCost,
	[initDueDate] = @initDueDate,
	[realDueDate] = @realDueDate,
	[promisedDate] = @promisedDate,
	[lastRecvDate] = @lastRecvDate,
	[descr] = @descr,
	[mfgId] = @mfgId,
	[viCode] = @viCode,
	[poUOfM] = @poUOfM,
	[poXStk] = @poXStk,
	[acctId] = @acctId,
	[idDist] = @idDist,
	[cmt] = @cmt,
	[taxCode1] = @taxCode1,
	[taxCode2] = @taxCode2,
	[taxCode3] = @taxCode3,
	[taxCode4] = @taxCode4,
	[taxCode5] = @taxCode5,
	[taxClass1] = @taxClass1,
	[taxClass2] = @taxClass2,
	[taxClass3] = @taxClass3,
	[taxClass4] = @taxClass4,
	[taxClass5] = @taxClass5,
	[taxBase1] = @taxBase1,
	[taxBase2] = @taxBase2,
	[taxBase3] = @taxBase3,
	[taxBase4] = @taxBase4,
	[taxBase5] = @taxBase5,
	[taxRate1] = @taxRate1,
	[taxRate2] = @taxRate2,
	[taxRate3] = @taxRate3,
	[taxRate4] = @taxRate4,
	[taxRate5] = @taxRate5,
	[taxAmt1] = @taxAmt1,
	[taxAmt2] = @taxAmt2,
	[taxAmt3] = @taxAmt3,
	[taxAmt4] = @taxAmt4,
	[taxAmt5] = @taxAmt5,
	[taxIncl1] = @taxIncl1,
	[taxIncl2] = @taxIncl2,
	[taxIncl3] = @taxIncl3,
	[taxIncl4] = @taxIncl4,
	[taxIncl5] = @taxIncl5,
	[rate] = @rate,
	[rateOper] = @rateOper,
	[lineNbr] = @lineNbr,
	[unitWgt] = @unitWgt,
	[addCost] = @addCost,
	[mohId] = @mohId,
	[momdId] = @momdId,
	[fldXml] = @fldXml
WHERE [pohId] = @pohIdOrig
  AND [pohRev] = @pohRevOrig
  AND [podId] = @podIdOrig
  AND rowVer = @TSCol

IF @@ROWCOUNT = 1
	SELECT @TSCol = rowVer FROM MIPOD
	WHERE [pohId] = @pohId
	  AND [pohRev] = @pohRev
	  AND [podId] = @podId
return @@rowcount

