/****** Object:  Procedure [dbo].[pr_MIOPTN_Update]    Committed by VersionSQL https://www.versionsql.com ******/



CREATE PROCEDURE dbo.pr_MIOPTN_Update
	@orgId nvarchar (12),
	@descr nvarchar (60),
	@orgType smallint,
	@coName nvarchar (60),
	@adr1 nvarchar (60),
	@adr2 nvarchar (60),
	@adr3 nvarchar (60),
	@adr4 nvarchar (60),
	@city nvarchar (30),
	@state nvarchar (30),
	@zip nvarchar (20),
	@country nvarchar (30),
	@phone nvarchar (30),
	@fax nvarchar (30),
	@email nvarchar (60),
	@contactName nvarchar (60),
	@contactEmail nvarchar (60),
	@homeCur nvarchar (3),
	@multiCurSw bit,
	@rateType nvarchar (2),
	@weightUnit nvarchar (10),
	@bomRevSw bit,
	@rollSw bit,
	@costMethod smallint,
	@multiLocSw bit,
	@jobTrackSw bit,
	@jobReqSw bit,
	@lotTrackSw bit,
	@lotAutoAssignSw bit,
	@lotTrackWipSw bit,
	@binTrackSw bit,
	@scAutoBldSw bit,
	@stAutoBldSw bit,
	@stConfirmSw bit,
	@stCompleteSw bit,
	@acctModule smallint,
	@apFeedSw bit,
	@glFeedSw bit,
	@icFeedSw bit,
	@oeFeedSw bit,
	@poFeedSw bit,
	@locOper smallint,
	@locGlSegNo smallint,
	@locSz smallint,
	@locDflt nvarchar (15),
	@itemOper smallint,
	@itemGlSegNo smallint,
	@itemSz smallint,
	@itemDflt nvarchar (15),
	@jobOper smallint,
	@jobGlSegNo smallint,
	@jobSz smallint,
	@jobDflt nvarchar (15),
	@jrnlNo int,
	@poQueueSw bit,
	@poTaxSw bit,
	@poRcvrSw bit,
	@negQtySw bit,
	@poIdInc smallint,
	@moIdInc smallint,
	@woIdInc smallint,
	@lotIdInc smallint,
	@srlIdInc smallint,
	@binIdInc smallint,
	@qDec smallint,
	@mDec smallint,
	@tDec smallint,
	@logTimeSw bit,
	@addCostSw bit,
	@docPath nvarchar (260),
	@picPath nvarchar (260),
	@spDate datetime,
	@versVer nvarchar (20),
	@versSerial nvarchar (20),
	@itemFmt nvarchar (40),
	@refFmt nvarchar (40),
	@pickFmt nvarchar (40),
	@salesFmt nvarchar (40),
	@telFmt nvarchar (40),
	@faxFmt nvarchar (40),
	@lotFmt nvarchar (60),
	@srlFmt nvarchar (60),
	@binFmt nvarchar (60),
	@companyURL nvarchar (260),
	@infoCenterURL nvarchar (260),
	@recCostSw smallint,
	@optInt1 smallint,
	@optInt2 smallint,
	@optStr1 nvarchar (60),
	@optStr2 nvarchar (60),
	@optXml text,
	@workWeek int,
	@orgIdOrig nvarchar (12),
	@TSCol rowversion output
AS
UPDATE MIOPTN
SET 	[orgId] = @orgId,
	[descr] = @descr,
	[orgType] = @orgType,
	[coName] = @coName,
	[adr1] = @adr1,
	[adr2] = @adr2,
	[adr3] = @adr3,
	[adr4] = @adr4,
	[city] = @city,
	[state] = @state,
	[zip] = @zip,
	[country] = @country,
	[phone] = @phone,
	[fax] = @fax,
	[email] = @email,
	[contactName] = @contactName,
	[contactEmail] = @contactEmail,
	[homeCur] = @homeCur,
	[multiCurSw] = @multiCurSw,
	[rateType] = @rateType,
	[weightUnit] = @weightUnit,
	[bomRevSw] = @bomRevSw,
	[rollSw] = @rollSw,
	[costMethod] = @costMethod,
	[multiLocSw] = @multiLocSw,
	[jobTrackSw] = @jobTrackSw,
	[jobReqSw] = @jobReqSw,
	[lotTrackSw] = @lotTrackSw,
	[lotAutoAssignSw] = @lotAutoAssignSw,
	[lotTrackWipSw] = @lotTrackWipSw,
	[binTrackSw] = @binTrackSw,
	[scAutoBldSw] = @scAutoBldSw,
	[stAutoBldSw] = @stAutoBldSw,
	[stConfirmSw] = @stConfirmSw,
	[stCompleteSw] = @stCompleteSw,
	[acctModule] = @acctModule,
	[apFeedSw] = @apFeedSw,
	[glFeedSw] = @glFeedSw,
	[icFeedSw] = @icFeedSw,
	[oeFeedSw] = @oeFeedSw,
	[poFeedSw] = @poFeedSw,
	[locOper] = @locOper,
	[locGlSegNo] = @locGlSegNo,
	[locSz] = @locSz,
	[locDflt] = @locDflt,
	[itemOper] = @itemOper,
	[itemGlSegNo] = @itemGlSegNo,
	[itemSz] = @itemSz,
	[itemDflt] = @itemDflt,
	[jobOper] = @jobOper,
	[jobGlSegNo] = @jobGlSegNo,
	[jobSz] = @jobSz,
	[jobDflt] = @jobDflt,
	[jrnlNo] = @jrnlNo,
	[poQueueSw] = @poQueueSw,
	[poTaxSw] = @poTaxSw,
	[poRcvrSw] = @poRcvrSw,
	[negQtySw] = @negQtySw,
	[poIdInc] = @poIdInc,
	[moIdInc] = @moIdInc,
	[woIdInc] = @woIdInc,
	[lotIdInc] = @lotIdInc,
	[srlIdInc] = @srlIdInc,
	[binIdInc] = @binIdInc,
	[qDec] = @qDec,
	[mDec] = @mDec,
	[tDec] = @tDec,
	[logTimeSw] = @logTimeSw,
	[addCostSw] = @addCostSw,
	[docPath] = @docPath,
	[picPath] = @picPath,
	[spDate] = @spDate,
	[versVer] = @versVer,
	[versSerial] = @versSerial,
	[itemFmt] = @itemFmt,
	[refFmt] = @refFmt,
	[pickFmt] = @pickFmt,
	[salesFmt] = @salesFmt,
	[telFmt] = @telFmt,
	[faxFmt] = @faxFmt,
	[lotFmt] = @lotFmt,
	[srlFmt] = @srlFmt,
	[binFmt] = @binFmt,
	[companyURL] = @companyURL,
	[infoCenterURL] = @infoCenterURL,
	[recCostSw] = @recCostSw,
	[optInt1] = @optInt1,
	[optInt2] = @optInt2,
	[optStr1] = @optStr1,
	[optStr2] = @optStr2,
	[optXml] = @optXml,
	[workWeek] = @workWeek
WHERE [orgId] = @orgIdOrig
  AND rowVer = @TSCol

IF @@ROWCOUNT = 1
	SELECT @TSCol = rowVer FROM MIOPTN
	WHERE [orgId] = @orgId
return @@rowcount

