/****** Object:  Procedure [dbo].[pr_MIITEM_Update]    Committed by VersionSQL https://www.versionsql.com ******/



CREATE PROCEDURE dbo.pr_MIITEM_Update
	@itemId nvarchar (24),
	@descr nvarchar (60),
	@xdesc nvarchar (2000),
	@ref nvarchar (24),
	@pick nvarchar (24),
	@sales nvarchar (256),
	@uOfM nvarchar (20),
	@poUOfM nvarchar (20),
	@uConvFact numeric (20, 6),
	@glId nvarchar (8),
	@segId nvarchar (15),
	@cycle int,
	@type smallint,
	@revId nvarchar (6),
	@track smallint,
	@lead int,
	@lstUseDate nvarchar (8),
	@lstPIDate nvarchar (8),
	@minLvl numeric (20, 6),
	@maxLvl numeric (20, 6),
	@ordLvl numeric (20, 6),
	@ordQty numeric (20, 6),
	@variance numeric (20, 6),
	@lotSz numeric (20, 6),
	@cLast numeric (20, 6),
	@cStd numeric (20, 6),
	@cAvg numeric (20, 6),
	@cLand numeric (20, 6),
	@unitWgt numeric (20, 6),
	@locId nvarchar (6),
	@suplId nvarchar (12),
	@mfgId nvarchar (12),
	@lotMeth smallint,
	@glAcct nvarchar (45),
	@apDist nvarchar (6),
	@a0Status smallint,
	@a0Func smallint,
	@a0Vol numeric (20, 6),
	@a0StartDate nvarchar (8),
	@a0EndDate nvarchar (8),
	@a0Off smallint,
	@a1Status smallint,
	@a1Func smallint,
	@a1Vol numeric (20, 6),
	@a1StartDate nvarchar (8),
	@a1EndDate nvarchar (8),
	@a1Off smallint,
	@a2Status smallint,
	@a2Func smallint,
	@a2Vol numeric (20, 6),
	@a2StartDate nvarchar (8),
	@a2EndDate nvarchar (8),
	@a2Off smallint,
	@status smallint,
	@bHuman bit,
	@fldXml text,
	@itemIdOrig nvarchar (24),
	@TSCol rowversion output
AS
UPDATE MIITEM
SET 	[itemId] = @itemId,
	[descr] = @descr,
	[xdesc] = @xdesc,
	[ref] = @ref,
	[pick] = @pick,
	[sales] = @sales,
	[uOfM] = @uOfM,
	[poUOfM] = @poUOfM,
	[uConvFact] = @uConvFact,
	[glId] = @glId,
	[segId] = @segId,
	[cycle] = @cycle,
	[type] = @type,
	[revId] = @revId,
	[track] = @track,
	[lead] = @lead,
	[lstUseDate] = @lstUseDate,
	[lstPIDate] = @lstPIDate,
	[minLvl] = @minLvl,
	[maxLvl] = @maxLvl,
	[ordLvl] = @ordLvl,
	[ordQty] = @ordQty,
	[variance] = @variance,
	[lotSz] = @lotSz,
	[cLast] = @cLast,
	[cStd] = @cStd,
	[cAvg] = @cAvg,
	[cLand] = @cLand,
	[unitWgt] = @unitWgt,
	[locId] = @locId,
	[suplId] = @suplId,
	[mfgId] = @mfgId,
	[lotMeth] = @lotMeth,
	[glAcct] = @glAcct,
	[apDist] = @apDist,
	[a0Status] = @a0Status,
	[a0Func] = @a0Func,
	[a0Vol] = @a0Vol,
	[a0StartDate] = @a0StartDate,
	[a0EndDate] = @a0EndDate,
	[a0Off] = @a0Off,
	[a1Status] = @a1Status,
	[a1Func] = @a1Func,
	[a1Vol] = @a1Vol,
	[a1StartDate] = @a1StartDate,
	[a1EndDate] = @a1EndDate,
	[a1Off] = @a1Off,
	[a2Status] = @a2Status,
	[a2Func] = @a2Func,
	[a2Vol] = @a2Vol,
	[a2StartDate] = @a2StartDate,
	[a2EndDate] = @a2EndDate,
	[a2Off] = @a2Off,
	[status] = @status,
	[bHuman] = @bHuman,
	[fldXml] = @fldXml
WHERE [itemId] = @itemIdOrig
  AND rowVer = @TSCol

IF @@ROWCOUNT = 1
	SELECT @TSCol = rowVer FROM MIITEM
	WHERE [itemId] = @itemId
return @@rowcount

