/****** Object:  Procedure [dbo].[pr_MIOPTN_Insert]    Committed by VersionSQL https://www.versionsql.com ******/




CREATE PROCEDURE dbo.pr_MIOPTN_Insert
	@orgId nvarchar (12),
	@descr nvarchar (60),
	@orgType smallint,
	@coName nvarchar (60),
	@adr1 nvarchar (60),
	@adr2 nvarchar (60),
	@adr3 nvarchar (60),
	@adr4 nvarchar (60),
	@city nvarchar (30),
	@state nvarchar (30),
	@zip nvarchar (20),
	@country nvarchar (30),
	@phone nvarchar (30),
	@fax nvarchar (30),
	@email nvarchar (60),
	@contactName nvarchar (60),
	@contactEmail nvarchar (60),
	@homeCur nvarchar (3),
	@multiCurSw bit,
	@rateType nvarchar (2),
	@weightUnit nvarchar (10),
	@bomRevSw bit,
	@rollSw bit,
	@costMethod smallint,
	@multiLocSw bit,
	@jobTrackSw bit,
	@jobReqSw bit,
	@lotTrackSw bit,
	@lotAutoAssignSw bit,
	@lotTrackWipSw bit,
	@binTrackSw bit,
	@scAutoBldSw bit,
	@stAutoBldSw bit,
	@stConfirmSw bit,
	@stCompleteSw bit,
	@acctModule smallint,
	@apFeedSw bit,
	@glFeedSw bit,
	@icFeedSw bit,
	@oeFeedSw bit,
	@poFeedSw bit,
	@locOper smallint,
	@locGlSegNo smallint,
	@locSz smallint,
	@locDflt nvarchar (15),
	@itemOper smallint,
	@itemGlSegNo smallint,
	@itemSz smallint,
	@itemDflt nvarchar (15),
	@jobOper smallint,
	@jobGlSegNo smallint,
	@jobSz smallint,
	@jobDflt nvarchar (15),
	@jrnlNo int,
	@poQueueSw bit,
	@poTaxSw bit,
	@poRcvrSw bit,
	@negQtySw bit,
	@poIdInc smallint,
	@moIdInc smallint,
	@woIdInc smallint,
	@lotIdInc smallint,
	@srlIdInc smallint,
	@binIdInc smallint,
	@qDec smallint,
	@mDec smallint,
	@tDec smallint,
	@logTimeSw bit,
	@addCostSw bit,
	@docPath nvarchar (260),
	@picPath nvarchar (260),
	@spDate datetime,
	@versVer nvarchar (20),
	@versSerial nvarchar (20),
	@itemFmt nvarchar (40),
	@refFmt nvarchar (40),
	@pickFmt nvarchar (40),
	@salesFmt nvarchar (40),
	@telFmt nvarchar (40),
	@faxFmt nvarchar (40),
	@lotFmt nvarchar (60),
	@srlFmt nvarchar (60),
	@binFmt nvarchar (60),
	@companyURL nvarchar (260),
	@infoCenterURL nvarchar (260),
	@recCostSw smallint,
	@optInt1 smallint,
	@optInt2 smallint,
	@optStr1 nvarchar (60),
	@optStr2 nvarchar (60),
	@optXml text,
	@workWeek int,
	@TSCol rowversion output 
AS
INSERT dbo.MIOPTN
(	[orgId],
	[descr],
	[orgType],
	[coName],
	[adr1],
	[adr2],
	[adr3],
	[adr4],
	[city],
	[state],
	[zip],
	[country],
	[phone],
	[fax],
	[email],
	[contactName],
	[contactEmail],
	[homeCur],
	[multiCurSw],
	[rateType],
	[weightUnit],
	[bomRevSw],
	[rollSw],
	[costMethod],
	[multiLocSw],
	[jobTrackSw],
	[jobReqSw],
	[lotTrackSw],
	[lotAutoAssignSw],
	[lotTrackWipSw],
	[binTrackSw],
	[scAutoBldSw],
	[stAutoBldSw],
	[stConfirmSw],
	[stCompleteSw],
	[acctModule],
	[apFeedSw],
	[glFeedSw],
	[icFeedSw],
	[oeFeedSw],
	[poFeedSw],
	[locOper],
	[locGlSegNo],
	[locSz],
	[locDflt],
	[itemOper],
	[itemGlSegNo],
	[itemSz],
	[itemDflt],
	[jobOper],
	[jobGlSegNo],
	[jobSz],
	[jobDflt],
	[jrnlNo],
	[poQueueSw],
	[poTaxSw],
	[poRcvrSw],
	[negQtySw],
	[poIdInc],
	[moIdInc],
	[woIdInc],
	[lotIdInc],
	[srlIdInc],
	[binIdInc],
	[qDec],
	[mDec],
	[tDec],
	[logTimeSw],
	[addCostSw],
	[docPath],
	[picPath],
	[spDate],
	[versVer],
	[versSerial],
	[itemFmt],
	[refFmt],
	[pickFmt],
	[salesFmt],
	[telFmt],
	[faxFmt],
	[lotFmt],
	[srlFmt],
	[binFmt],
	[companyURL],
	[infoCenterURL],
	[recCostSw],
	[optInt1],
	[optInt2],
	[optStr1],
	[optStr2],
	[optXml],
	[workWeek]
)
VALUES
(
	@orgId,
	@descr,
	@orgType,
	@coName,
	@adr1,
	@adr2,
	@adr3,
	@adr4,
	@city,
	@state,
	@zip,
	@country,
	@phone,
	@fax,
	@email,
	@contactName,
	@contactEmail,
	@homeCur,
	@multiCurSw,
	@rateType,
	@weightUnit,
	@bomRevSw,
	@rollSw,
	@costMethod,
	@multiLocSw,
	@jobTrackSw,
	@jobReqSw,
	@lotTrackSw,
	@lotAutoAssignSw,
	@lotTrackWipSw,
	@binTrackSw,
	@scAutoBldSw,
	@stAutoBldSw,
	@stConfirmSw,
	@stCompleteSw,
	@acctModule,
	@apFeedSw,
	@glFeedSw,
	@icFeedSw,
	@oeFeedSw,
	@poFeedSw,
	@locOper,
	@locGlSegNo,
	@locSz,
	@locDflt,
	@itemOper,
	@itemGlSegNo,
	@itemSz,
	@itemDflt,
	@jobOper,
	@jobGlSegNo,
	@jobSz,
	@jobDflt,
	@jrnlNo,
	@poQueueSw,
	@poTaxSw,
	@poRcvrSw,
	@negQtySw,
	@poIdInc,
	@moIdInc,
	@woIdInc,
	@lotIdInc,
	@srlIdInc,
	@binIdInc,
	@qDec,
	@mDec,
	@tDec,
	@logTimeSw,
	@addCostSw,
	@docPath,
	@picPath,
	@spDate,
	@versVer,
	@versSerial,
	@itemFmt,
	@refFmt,
	@pickFmt,
	@salesFmt,
	@telFmt,
	@faxFmt,
	@lotFmt,
	@srlFmt,
	@binFmt,
	@companyURL,
	@infoCenterURL,
	@recCostSw,
	@optInt1,
	@optInt2,
	@optStr1,
	@optStr2,
	@optXml,
	@workWeek
)
IF @@ROWCOUNT = 1
	SELECT @TSCol = rowVer
	  FROM MIOPTN
	  WHERE [orgId] = @orgId
return @@rowcount

