/****** Object:  Procedure [dbo].[pr_MIPOCV_Insert]    Committed by VersionSQL https://www.versionsql.com ******/




CREATE PROCEDURE dbo.pr_MIPOCV_Insert
	@pohId nvarchar (12),
	@pohRev smallint,
	@poSuplId nvarchar (12),
	@name nvarchar (60),
	@adr1 nvarchar (60),
	@adr2 nvarchar (60),
	@adr3 nvarchar (60),
	@adr4 nvarchar (60),
	@city nvarchar (30),
	@state nvarchar (30),
	@zip nvarchar (20),
	@country nvarchar (30),
	@phone nvarchar (30),
	@fax nvarchar (30),
	@contact nvarchar (60),
	@email nvarchar (50),
	@terms nvarchar (6),
	@curId nvarchar (3),
	@rateType nvarchar (2),
	@rateDate nvarchar (8),
	@rate numeric (20, 6),
	@spread numeric (20, 6),
	@dateMatch int,
	@rateOper int,
	@txGroup nvarchar (12),
	@taxCode1 nvarchar (12),
	@taxCode2 nvarchar (12),
	@taxCode3 nvarchar (12),
	@taxCode4 nvarchar (12),
	@taxCode5 nvarchar (12),
	@taxClass1 int,
	@taxClass2 int,
	@taxClass3 int,
	@taxClass4 int,
	@taxClass5 int,
	@TSCol rowversion output 
AS
INSERT dbo.MIPOCV
(	[pohId],
	[pohRev],
	[poSuplId],
	[name],
	[adr1],
	[adr2],
	[adr3],
	[adr4],
	[city],
	[state],
	[zip],
	[country],
	[phone],
	[fax],
	[contact],
	[email],
	[terms],
	[curId],
	[rateType],
	[rateDate],
	[rate],
	[spread],
	[dateMatch],
	[rateOper],
	[txGroup],
	[taxCode1],
	[taxCode2],
	[taxCode3],
	[taxCode4],
	[taxCode5],
	[taxClass1],
	[taxClass2],
	[taxClass3],
	[taxClass4],
	[taxClass5]
)
VALUES
(
	@pohId,
	@pohRev,
	@poSuplId,
	@name,
	@adr1,
	@adr2,
	@adr3,
	@adr4,
	@city,
	@state,
	@zip,
	@country,
	@phone,
	@fax,
	@contact,
	@email,
	@terms,
	@curId,
	@rateType,
	@rateDate,
	@rate,
	@spread,
	@dateMatch,
	@rateOper,
	@txGroup,
	@taxCode1,
	@taxCode2,
	@taxCode3,
	@taxCode4,
	@taxCode5,
	@taxClass1,
	@taxClass2,
	@taxClass3,
	@taxClass4,
	@taxClass5
)
IF @@ROWCOUNT = 1
	SELECT @TSCol = rowVer
	  FROM MIPOCV
	  WHERE [pohId] = @pohId
	   AND [pohRev] = @pohRev
	   AND [poSuplId] = @poSuplId
return @@rowcount

