/****** Object:  Procedure [dbo].[pr_MISCHAUTX_Insert]    Committed by VersionSQL https://www.versionsql.com ******/




CREATE PROCEDURE dbo.pr_MISCHAUTX_Insert
	@schNum int,
	@schLine int,
	@uniqueId int,
	@schId nvarchar (6),
	@itemId nvarchar (24),
	@locId nvarchar (6),
	@dateISO nvarchar (8),
	@actISODate nvarchar (8),
	@qnt numeric (20, 6),
	@stock numeric (20, 6),
	@type smallint,
	@revId nvarchar (6),
	@levId smallint,
	@whenId smallint,
	@topType smallint,
	@topItem nvarchar (24),
	@topRevId nvarchar (6),
	@topQnt numeric (20, 6),
	@topISODate nvarchar (8),
	@POId nvarchar (12),
	@WOId nvarchar (12),
	@MOId nvarchar (15),
	@SOId nvarchar (256),
	@Detail int,
	@SrcLocId nvarchar (6),
	@topComment nvarchar (256),
	@ProcIndex smallint,
	@PORev smallint,
	@opCode nvarchar (24),
	@customer nvarchar (256),
	@subQnt numeric (20, 6)
AS
INSERT dbo.MISCHAUTX
(	[schNum],
	[schLine],
	[uniqueId],
	[schId],
	[itemId],
	[locId],
	[dateISO],
	[actISODate],
	[qnt],
	[stock],
	[type],
	[revId],
	[levId],
	[whenId],
	[topType],
	[topItem],
	[topRevId],
	[topQnt],
	[topISODate],
	[POId],
	[WOId],
	[MOId],
	[SOId],
	[Detail],
	[SrcLocId],
	[topComment],
	[ProcIndex],
	[PORev],
	[opCode],
	[customer],
	[subQnt]
)
VALUES
(
	@schNum,
	@schLine,
	@uniqueId,
	@schId,
	@itemId,
	@locId,
	@dateISO,
	@actISODate,
	@qnt,
	@stock,
	@type,
	@revId,
	@levId,
	@whenId,
	@topType,
	@topItem,
	@topRevId,
	@topQnt,
	@topISODate,
	@POId,
	@WOId,
	@MOId,
	@SOId,
	@Detail,
	@SrcLocId,
	@topComment,
	@ProcIndex,
	@PORev,
	@opCode,
	@customer,
	@subQnt
)
IF @@ROWCOUNT = 1
return @@rowcount

