/****** Object:  Procedure [dbo].[pr_MIITEM_Insert]    Committed by VersionSQL https://www.versionsql.com ******/




CREATE PROCEDURE dbo.pr_MIITEM_Insert
	@itemId nvarchar (24),
	@descr nvarchar (60),
	@xdesc nvarchar (2000),
	@ref nvarchar (24),
	@pick nvarchar (24),
	@sales nvarchar (256),
	@uOfM nvarchar (20),
	@poUOfM nvarchar (20),
	@uConvFact numeric (20, 6),
	@glId nvarchar (8),
	@segId nvarchar (15),
	@cycle int,
	@type smallint,
	@revId nvarchar (6),
	@track smallint,
	@lead int,
	@lstUseDate nvarchar (8),
	@lstPIDate nvarchar (8),
	@minLvl numeric (20, 6),
	@maxLvl numeric (20, 6),
	@ordLvl numeric (20, 6),
	@ordQty numeric (20, 6),
	@variance numeric (20, 6),
	@lotSz numeric (20, 6),
	@cLast numeric (20, 6),
	@cStd numeric (20, 6),
	@cAvg numeric (20, 6),
	@cLand numeric (20, 6),
	@unitWgt numeric (20, 6),
	@locId nvarchar (6),
	@suplId nvarchar (12),
	@mfgId nvarchar (12),
	@lotMeth smallint,
	@glAcct nvarchar (45),
	@apDist nvarchar (6),
	@a0Status smallint,
	@a0Func smallint,
	@a0Vol numeric (20, 6),
	@a0StartDate nvarchar (8),
	@a0EndDate nvarchar (8),
	@a0Off smallint,
	@a1Status smallint,
	@a1Func smallint,
	@a1Vol numeric (20, 6),
	@a1StartDate nvarchar (8),
	@a1EndDate nvarchar (8),
	@a1Off smallint,
	@a2Status smallint,
	@a2Func smallint,
	@a2Vol numeric (20, 6),
	@a2StartDate nvarchar (8),
	@a2EndDate nvarchar (8),
	@a2Off smallint,
	@status smallint,
	@bHuman bit,
	@fldXml text,
	@TSCol rowversion output 
AS
INSERT dbo.MIITEM
(	[itemId],
	[descr],
	[xdesc],
	[ref],
	[pick],
	[sales],
	[uOfM],
	[poUOfM],
	[uConvFact],
	[glId],
	[segId],
	[cycle],
	[type],
	[revId],
	[track],
	[lead],
	[lstUseDate],
	[lstPIDate],
	[minLvl],
	[maxLvl],
	[ordLvl],
	[ordQty],
	[variance],
	[lotSz],
	[cLast],
	[cStd],
	[cAvg],
	[cLand],
	[unitWgt],
	[locId],
	[suplId],
	[mfgId],
	[lotMeth],
	[glAcct],
	[apDist],
	[a0Status],
	[a0Func],
	[a0Vol],
	[a0StartDate],
	[a0EndDate],
	[a0Off],
	[a1Status],
	[a1Func],
	[a1Vol],
	[a1StartDate],
	[a1EndDate],
	[a1Off],
	[a2Status],
	[a2Func],
	[a2Vol],
	[a2StartDate],
	[a2EndDate],
	[a2Off],
	[status],
	[bHuman],
	[fldXml]
)
VALUES
(
	@itemId,
	@descr,
	@xdesc,
	@ref,
	@pick,
	@sales,
	@uOfM,
	@poUOfM,
	@uConvFact,
	@glId,
	@segId,
	@cycle,
	@type,
	@revId,
	@track,
	@lead,
	@lstUseDate,
	@lstPIDate,
	@minLvl,
	@maxLvl,
	@ordLvl,
	@ordQty,
	@variance,
	@lotSz,
	@cLast,
	@cStd,
	@cAvg,
	@cLand,
	@unitWgt,
	@locId,
	@suplId,
	@mfgId,
	@lotMeth,
	@glAcct,
	@apDist,
	@a0Status,
	@a0Func,
	@a0Vol,
	@a0StartDate,
	@a0EndDate,
	@a0Off,
	@a1Status,
	@a1Func,
	@a1Vol,
	@a1StartDate,
	@a1EndDate,
	@a1Off,
	@a2Status,
	@a2Func,
	@a2Vol,
	@a2StartDate,
	@a2EndDate,
	@a2Off,
	@status,
	@bHuman,
	@fldXml
)
IF @@ROWCOUNT = 1
	SELECT @TSCol = rowVer
	  FROM MIITEM
	  WHERE [itemId] = @itemId
return @@rowcount

