/****** Object:  Procedure [dbo].[pr_MIMOH_Insert]    Committed by VersionSQL https://www.versionsql.com ******/




CREATE PROCEDURE dbo.pr_MIMOH_Insert
	@mohId nvarchar (15),
	@lstMaintDt datetime,
	@descr nvarchar (60),
	@notes nvarchar (2000),
	@creator nvarchar (8),
	@releaser nvarchar (8),
	@jobId nvarchar (12),
	@locId nvarchar (6),
	@buildItem nvarchar (24),
	@buildNonItem bit,
	@buildNonItemDesc nvarchar (60),
	@bomItem nvarchar (24),
	@bomRev nvarchar (6),
	@moStat smallint,
	@prStat smallint,
	@ordQty numeric (20, 6),
	@ordDate nvarchar (8),
	@startDate nvarchar (8),
	@endDate nvarchar (8),
	@releaseDate nvarchar (8),
	@relOrdQty numeric (20, 6),
	@releaseCost numeric (20, 6),
	@relLabCost numeric (20, 6),
	@relOvrhdCost numeric (20, 6),
	@priority smallint,
	@markup numeric (20, 6),
	@wipQty numeric (20, 6),
	@resQty numeric (20, 6),
	@endQty numeric (20, 6),
	@closeDate nvarchar (8),
	@hdrTxt1 nvarchar (30),
	@hdrTxt2 nvarchar (30),
	@hdrTxt3 nvarchar (30),
	@hdrTxt4 nvarchar (30),
	@docPath nvarchar (260),
	@oeOrdNo nvarchar (256),
	@oeOrdDtLn int,
	@icTransQty numeric (20, 6),
	@onHold bit,
	@fldXml text,
	@icLoc nvarchar (256),
	@customer nvarchar (256),
	@soShipDate nvarchar (8),
	@chkValidEndDt bit,
	@buildSales nvarchar (256),
	@cumCost numeric (20, 6),
	@TSCol rowversion output 
AS
INSERT dbo.MIMOH
(	[mohId],
	[lstMaintDt],
	[descr],
	[notes],
	[creator],
	[releaser],
	[jobId],
	[locId],
	[buildItem],
	[buildNonItem],
	[buildNonItemDesc],
	[bomItem],
	[bomRev],
	[moStat],
	[prStat],
	[ordQty],
	[ordDate],
	[startDate],
	[endDate],
	[releaseDate],
	[relOrdQty],
	[releaseCost],
	[relLabCost],
	[relOvrhdCost],
	[priority],
	[markup],
	[wipQty],
	[resQty],
	[endQty],
	[closeDate],
	[hdrTxt1],
	[hdrTxt2],
	[hdrTxt3],
	[hdrTxt4],
	[docPath],
	[oeOrdNo],
	[oeOrdDtLn],
	[icTransQty],
	[onHold],
	[fldXml],
	[icLoc],
	[customer],
	[soShipDate],
	[chkValidEndDt],
	[buildSales],
	[cumCost]
)
VALUES
(
	@mohId,
	@lstMaintDt,
	@descr,
	@notes,
	@creator,
	@releaser,
	@jobId,
	@locId,
	@buildItem,
	@buildNonItem,
	@buildNonItemDesc,
	@bomItem,
	@bomRev,
	@moStat,
	@prStat,
	@ordQty,
	@ordDate,
	@startDate,
	@endDate,
	@releaseDate,
	@relOrdQty,
	@releaseCost,
	@relLabCost,
	@relOvrhdCost,
	@priority,
	@markup,
	@wipQty,
	@resQty,
	@endQty,
	@closeDate,
	@hdrTxt1,
	@hdrTxt2,
	@hdrTxt3,
	@hdrTxt4,
	@docPath,
	@oeOrdNo,
	@oeOrdDtLn,
	@icTransQty,
	@onHold,
	@fldXml,
	@icLoc,
	@customer,
	@soShipDate,
	@chkValidEndDt,
	@buildSales,
	@cumCost
)
IF @@ROWCOUNT = 1
	SELECT @TSCol = rowVer
	  FROM MIMOH
	  WHERE [mohId] = @mohId
return @@rowcount

