/****** Object:  Procedure [dbo].[pr_MIEBX_Insert]    Committed by VersionSQL https://www.versionsql.com ******/




CREATE PROCEDURE dbo.pr_MIEBX_Insert
	@uniq int,
	@mohId0 nvarchar (15),
	@itemId0 nvarchar (24),
	@revn0 nvarchar (6),
	@qty0 numeric (20, 6),
	@mohId1 nvarchar (15),
	@itemId1 nvarchar (24),
	@revn1 nvarchar (6),
	@qty1 numeric (20, 6),
	@mohId2 nvarchar (15),
	@itemId2 nvarchar (24),
	@revn2 nvarchar (6),
	@qty2 numeric (20, 6),
	@mohId3 nvarchar (15),
	@itemId3 nvarchar (24),
	@revn3 nvarchar (6),
	@qty3 numeric (20, 6),
	@mohId4 nvarchar (15),
	@itemId4 nvarchar (24),
	@revn4 nvarchar (6),
	@qty4 numeric (20, 6),
	@mohId5 nvarchar (15),
	@itemId5 nvarchar (24),
	@revn5 nvarchar (6),
	@qty5 numeric (20, 6),
	@mohId6 nvarchar (15),
	@itemId6 nvarchar (24),
	@revn6 nvarchar (6),
	@qty6 numeric (20, 6),
	@mohId7 nvarchar (15),
	@itemId7 nvarchar (24),
	@revn7 nvarchar (6),
	@qty7 numeric (20, 6),
	@mohId8 nvarchar (15),
	@itemId8 nvarchar (24),
	@revn8 nvarchar (6),
	@qty8 numeric (20, 6),
	@mohId9 nvarchar (15),
	@itemId9 nvarchar (24),
	@revn9 nvarchar (6),
	@qty9 numeric (20, 6),
	@mohId10 nvarchar (15),
	@itemId10 nvarchar (24),
	@revn10 nvarchar (6),
	@qty10 numeric (20, 6),
	@mohId11 nvarchar (15),
	@itemId11 nvarchar (24),
	@revn11 nvarchar (6),
	@qty11 numeric (20, 6),
	@mohId12 nvarchar (15),
	@itemId12 nvarchar (24),
	@revn12 nvarchar (6),
	@qty12 numeric (20, 6),
	@mohId13 nvarchar (15),
	@itemId13 nvarchar (24),
	@revn13 nvarchar (6),
	@qty13 numeric (20, 6),
	@mohId14 nvarchar (15),
	@itemId14 nvarchar (24),
	@revn14 nvarchar (6),
	@qty14 numeric (20, 6),
	@mohId15 nvarchar (15),
	@itemId15 nvarchar (24),
	@revn15 nvarchar (6),
	@qty15 numeric (20, 6),
	@mohId16 nvarchar (15),
	@itemId16 nvarchar (24),
	@revn16 nvarchar (6),
	@qty16 numeric (20, 6),
	@hiMohId nvarchar (15),
	@hiMomdId int,
	@hiCmohId nvarchar (15),
	@hiItemId nvarchar (24),
	@hiRevn nvarchar (6),
	@hiEntry int,
	@hiLevel smallint,
	@hiQty numeric (20, 6),
	@hiLead smallint,
	@hiCmnt nvarchar (60),
	@hiLocId nvarchar (6),
	@hiWodLn smallint,
	@pick nvarchar (24),
	@minLvl numeric (20, 6),
	@maxLvl numeric (20, 6),
	@ordLvl numeric (20, 6),
	@ordQty numeric (20, 6),
	@lstPIDate nvarchar (8),
	@variance numeric (20, 6),
	@qStk numeric (20, 6),
	@qWip numeric (20, 6),
	@qRes numeric (20, 6),
	@qOrd numeric (20, 6),
	@iqStk numeric (20, 6),
	@iqWip numeric (20, 6),
	@iqRes numeric (20, 6),
	@iqOrd numeric (20, 6),
	@opCode nvarchar (24),
	@rdLineNbr smallint,
	@src smallint,
	@dType smallint,
	@wcId nvarchar (24),
	@toolId nvarchar (12),
	@hiItemUnitCost numeric (20, 6),
	@TSCol rowversion output 
AS
INSERT dbo.MIEBX
(	[uniq],
	[mohId0],
	[itemId0],
	[revn0],
	[qty0],
	[mohId1],
	[itemId1],
	[revn1],
	[qty1],
	[mohId2],
	[itemId2],
	[revn2],
	[qty2],
	[mohId3],
	[itemId3],
	[revn3],
	[qty3],
	[mohId4],
	[itemId4],
	[revn4],
	[qty4],
	[mohId5],
	[itemId5],
	[revn5],
	[qty5],
	[mohId6],
	[itemId6],
	[revn6],
	[qty6],
	[mohId7],
	[itemId7],
	[revn7],
	[qty7],
	[mohId8],
	[itemId8],
	[revn8],
	[qty8],
	[mohId9],
	[itemId9],
	[revn9],
	[qty9],
	[mohId10],
	[itemId10],
	[revn10],
	[qty10],
	[mohId11],
	[itemId11],
	[revn11],
	[qty11],
	[mohId12],
	[itemId12],
	[revn12],
	[qty12],
	[mohId13],
	[itemId13],
	[revn13],
	[qty13],
	[mohId14],
	[itemId14],
	[revn14],
	[qty14],
	[mohId15],
	[itemId15],
	[revn15],
	[qty15],
	[mohId16],
	[itemId16],
	[revn16],
	[qty16],
	[hiMohId],
	[hiMomdId],
	[hiCmohId],
	[hiItemId],
	[hiRevn],
	[hiEntry],
	[hiLevel],
	[hiQty],
	[hiLead],
	[hiCmnt],
	[hiLocId],
	[hiWodLn],
	[pick],
	[minLvl],
	[maxLvl],
	[ordLvl],
	[ordQty],
	[lstPIDate],
	[variance],
	[qStk],
	[qWip],
	[qRes],
	[qOrd],
	[iqStk],
	[iqWip],
	[iqRes],
	[iqOrd],
	[opCode],
	[rdLineNbr],
	[src],
	[dType],
	[wcId],
	[toolId],
	[hiItemUnitCost]
)
VALUES
(
	@uniq,
	@mohId0,
	@itemId0,
	@revn0,
	@qty0,
	@mohId1,
	@itemId1,
	@revn1,
	@qty1,
	@mohId2,
	@itemId2,
	@revn2,
	@qty2,
	@mohId3,
	@itemId3,
	@revn3,
	@qty3,
	@mohId4,
	@itemId4,
	@revn4,
	@qty4,
	@mohId5,
	@itemId5,
	@revn5,
	@qty5,
	@mohId6,
	@itemId6,
	@revn6,
	@qty6,
	@mohId7,
	@itemId7,
	@revn7,
	@qty7,
	@mohId8,
	@itemId8,
	@revn8,
	@qty8,
	@mohId9,
	@itemId9,
	@revn9,
	@qty9,
	@mohId10,
	@itemId10,
	@revn10,
	@qty10,
	@mohId11,
	@itemId11,
	@revn11,
	@qty11,
	@mohId12,
	@itemId12,
	@revn12,
	@qty12,
	@mohId13,
	@itemId13,
	@revn13,
	@qty13,
	@mohId14,
	@itemId14,
	@revn14,
	@qty14,
	@mohId15,
	@itemId15,
	@revn15,
	@qty15,
	@mohId16,
	@itemId16,
	@revn16,
	@qty16,
	@hiMohId,
	@hiMomdId,
	@hiCmohId,
	@hiItemId,
	@hiRevn,
	@hiEntry,
	@hiLevel,
	@hiQty,
	@hiLead,
	@hiCmnt,
	@hiLocId,
	@hiWodLn,
	@pick,
	@minLvl,
	@maxLvl,
	@ordLvl,
	@ordQty,
	@lstPIDate,
	@variance,
	@qStk,
	@qWip,
	@qRes,
	@qOrd,
	@iqStk,
	@iqWip,
	@iqRes,
	@iqOrd,
	@opCode,
	@rdLineNbr,
	@src,
	@dType,
	@wcId,
	@toolId,
	@hiItemUnitCost
)
IF @@ROWCOUNT = 1
	SELECT @TSCol = rowVer
	  FROM MIEBX
	  WHERE [uniq] = @uniq
return @@rowcount

