/****** Object:  Table [dbo].[MIACSTX]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MIACSTX](
	[addCostId] [nvarchar](8) NOT NULL,
	[auth] [nvarchar](12) NOT NULL,
	[curCode] [nvarchar](3) NULL,
	[taxClass] [smallint] NOT NULL,
	[rowVer] [timestamp] NOT NULL,
 CONSTRAINT [PK_MIACSTX_KEY_0] PRIMARY KEY CLUSTERED 
(
	[addCostId] ASC,
	[auth] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[MIACSTX] ADD  DEFAULT (' ') FOR [addCostId]
ALTER TABLE [dbo].[MIACSTX] ADD  DEFAULT ((1)) FOR [taxClass]
ALTER TABLE [dbo].[MIACSTX]  WITH CHECK ADD FOREIGN KEY([auth])
REFERENCES [dbo].[MITXAUTH] ([auth])
ALTER TABLE [dbo].[MIACSTX]  WITH CHECK ADD FOREIGN KEY([curCode])
REFERENCES [dbo].[MICCD] ([curId])
ALTER TABLE [dbo].[MIACSTX]  WITH CHECK ADD  CONSTRAINT [FK_MIACSTX_MIACST] FOREIGN KEY([addCostId])
REFERENCES [dbo].[MIACST] ([addCostId])
ON DELETE CASCADE
ALTER TABLE [dbo].[MIACSTX] CHECK CONSTRAINT [FK_MIACSTX_MIACST]
