/****** Object:  Table [dbo].[MIBINQ]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MIBINQ](
	[locId] [nvarchar](6) NOT NULL,
	[binId] [nvarchar](24) NOT NULL,
	[seqNo] [nvarchar](6) NOT NULL,
	[createDate] [nvarchar](8) NULL,
	[lstUseDate] [nvarchar](8) NULL,
	[descr] [nvarchar](30) NOT NULL,
	[status] [smallint] NOT NULL,
	[itemId] [nvarchar](24) NULL,
	[qStk] [numeric](20, 6) NOT NULL,
	[fldXml] [text] NOT NULL,
	[createDt]  AS (CONVERT([datetime],[createDate])),
	[lstUseDt]  AS (CONVERT([datetime],[lstUseDate])),
	[rowVer] [timestamp] NOT NULL,
 CONSTRAINT [PK_MIBINQ_KEY_0] PRIMARY KEY CLUSTERED 
(
	[locId] ASC,
	[binId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IDX_MIBINQ_1] ON [dbo].[MIBINQ]
(
	[locId] ASC,
	[seqNo] ASC,
	[binId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IDX_MIBINQ_2] ON [dbo].[MIBINQ]
(
	[itemId] ASC,
	[locId] ASC,
	[binId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[MIBINQ] ADD  DEFAULT (' ') FOR [locId]
ALTER TABLE [dbo].[MIBINQ] ADD  DEFAULT (' ') FOR [binId]
ALTER TABLE [dbo].[MIBINQ] ADD  DEFAULT ('000000') FOR [seqNo]
ALTER TABLE [dbo].[MIBINQ] ADD  DEFAULT (' ') FOR [descr]
ALTER TABLE [dbo].[MIBINQ] ADD  DEFAULT ((0)) FOR [status]
ALTER TABLE [dbo].[MIBINQ] ADD  DEFAULT ((0)) FOR [qStk]
ALTER TABLE [dbo].[MIBINQ] ADD  DEFAULT (' ') FOR [fldXml]
ALTER TABLE [dbo].[MIBINQ]  WITH CHECK ADD FOREIGN KEY([itemId])
REFERENCES [dbo].[MIITEM] ([itemId])
ALTER TABLE [dbo].[MIBINQ]  WITH CHECK ADD  CONSTRAINT [FK_MIBINQ_MIDLOC] FOREIGN KEY([locId])
REFERENCES [dbo].[MIDLOC] ([locId])
ON DELETE CASCADE
ALTER TABLE [dbo].[MIBINQ] CHECK CONSTRAINT [FK_MIBINQ_MIDLOC]
