/****** Object:  Table [dbo].[MIITTX]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MIITTX](
	[itemId] [nvarchar](24) NOT NULL,
	[auth] [nvarchar](12) NOT NULL,
	[taxClass] [int] NOT NULL,
	[taxIncl] [smallint] NOT NULL,
	[altBase1] [numeric](20, 6) NOT NULL,
	[altBase2] [numeric](20, 6) NOT NULL,
	[rowVer] [timestamp] NOT NULL,
 CONSTRAINT [PK_MIITTX_KEY_0] PRIMARY KEY CLUSTERED 
(
	[itemId] ASC,
	[auth] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[MIITTX] ADD  DEFAULT (' ') FOR [itemId]
ALTER TABLE [dbo].[MIITTX] ADD  DEFAULT ((1)) FOR [taxClass]
ALTER TABLE [dbo].[MIITTX] ADD  DEFAULT ((0)) FOR [taxIncl]
ALTER TABLE [dbo].[MIITTX] ADD  DEFAULT ((0)) FOR [altBase1]
ALTER TABLE [dbo].[MIITTX] ADD  DEFAULT ((0)) FOR [altBase2]
ALTER TABLE [dbo].[MIITTX]  WITH CHECK ADD FOREIGN KEY([auth])
REFERENCES [dbo].[MITXAUTH] ([auth])
ALTER TABLE [dbo].[MIITTX]  WITH CHECK ADD  CONSTRAINT [FK_MIITTX_MIITEM] FOREIGN KEY([itemId])
REFERENCES [dbo].[MIITEM] ([itemId])
ON DELETE CASCADE
ALTER TABLE [dbo].[MIITTX] CHECK CONSTRAINT [FK_MIITTX_MIITEM]
