/****** Object:  Table [dbo].[MIITEMX]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MIITEMX](
	[itemId] [nvarchar](24) NOT NULL,
	[notes] [nvarchar](2000) NOT NULL,
	[docPath] [nvarchar](260) NOT NULL,
	[picPath] [nvarchar](260) NOT NULL,
	[rowVer] [timestamp] NOT NULL,
 CONSTRAINT [PK_MIITEMX_KEY_0] PRIMARY KEY CLUSTERED 
(
	[itemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[MIITEMX] ADD  DEFAULT (' ') FOR [itemId]
ALTER TABLE [dbo].[MIITEMX] ADD  DEFAULT (' ') FOR [notes]
ALTER TABLE [dbo].[MIITEMX] ADD  DEFAULT (' ') FOR [docPath]
ALTER TABLE [dbo].[MIITEMX] ADD  DEFAULT (' ') FOR [picPath]
ALTER TABLE [dbo].[MIITEMX]  WITH CHECK ADD  CONSTRAINT [FK_MIITEMX_MIITEM] FOREIGN KEY([itemId])
REFERENCES [dbo].[MIITEM] ([itemId])
ON DELETE CASCADE
ALTER TABLE [dbo].[MIITEMX] CHECK CONSTRAINT [FK_MIITEMX_MIITEM]
