/****** Object:  Table [dbo].[MIQMFG]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MIQMFG](
	[itemId] [nvarchar](24) NOT NULL,
	[mfgId] [nvarchar](12) NOT NULL,
	[mfgName] [nvarchar](60) NOT NULL,
	[mfgProdCode] [nvarchar](24) NOT NULL,
	[rowVer] [timestamp] NOT NULL,
 CONSTRAINT [PK_MIQMFG_KEY_0] PRIMARY KEY CLUSTERED 
(
	[itemId] ASC,
	[mfgId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [IDX_MIQMFG_1] ON [dbo].[MIQMFG]
(
	[mfgId] ASC,
	[itemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[MIQMFG] ADD  DEFAULT (' ') FOR [itemId]
ALTER TABLE [dbo].[MIQMFG] ADD  DEFAULT ('NEWMFG') FOR [mfgId]
ALTER TABLE [dbo].[MIQMFG] ADD  DEFAULT (' ') FOR [mfgName]
ALTER TABLE [dbo].[MIQMFG] ADD  DEFAULT (' ') FOR [mfgProdCode]
ALTER TABLE [dbo].[MIQMFG]  WITH CHECK ADD  CONSTRAINT [FK_MIQMFG_MIITEM] FOREIGN KEY([itemId])
REFERENCES [dbo].[MIITEM] ([itemId])
ON DELETE CASCADE
ALTER TABLE [dbo].[MIQMFG] CHECK CONSTRAINT [FK_MIQMFG_MIITEM]
