/****** Object:  Table [dbo].[MISCHITEM]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MISCHITEM](
	[schNum] [int] NOT NULL,
	[schLine] [int] NOT NULL,
	[schId] [nvarchar](6) NULL,
	[itemId] [nvarchar](24) NOT NULL,
	[locId] [nvarchar](6) NOT NULL,
	[firstShortQty] [numeric](20, 6) NOT NULL,
	[firstShortDate] [nvarchar](8) NULL,
	[maxShortQty] [numeric](20, 6) NOT NULL,
	[maxShortDate] [nvarchar](8) NULL,
	[maxQty] [numeric](20, 6) NOT NULL,
	[basisQty] [numeric](20, 6) NOT NULL,
	[firstShortDt]  AS (CONVERT([datetime],[firstShortDate])),
	[maxShortDt]  AS (CONVERT([datetime],[maxShortDate])),
 CONSTRAINT [PK_MISCHITEM_KEY_0] PRIMARY KEY CLUSTERED 
(
	[schNum] ASC,
	[schLine] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [IDX_MISCHITEM_1] ON [dbo].[MISCHITEM]
(
	[schId] ASC,
	[itemId] ASC,
	[locId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IDX_MISCHITEM_2] ON [dbo].[MISCHITEM]
(
	[schId] ASC,
	[firstShortDate] ASC,
	[itemId] ASC,
	[locId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IDX_MISCHITEM_3] ON [dbo].[MISCHITEM]
(
	[schId] ASC,
	[firstShortQty] ASC,
	[firstShortDate] ASC,
	[itemId] ASC,
	[locId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IDX_MISCHITEM_4] ON [dbo].[MISCHITEM]
(
	[schId] ASC,
	[maxShortQty] ASC,
	[maxShortDate] ASC,
	[itemId] ASC,
	[locId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[MISCHITEM] ADD  DEFAULT ((0)) FOR [schNum]
ALTER TABLE [dbo].[MISCHITEM] ADD  DEFAULT ((0)) FOR [schLine]
ALTER TABLE [dbo].[MISCHITEM] ADD  DEFAULT (' ') FOR [itemId]
ALTER TABLE [dbo].[MISCHITEM] ADD  DEFAULT (' ') FOR [locId]
ALTER TABLE [dbo].[MISCHITEM] ADD  DEFAULT ((0)) FOR [firstShortQty]
ALTER TABLE [dbo].[MISCHITEM] ADD  DEFAULT ((0)) FOR [maxShortQty]
ALTER TABLE [dbo].[MISCHITEM] ADD  DEFAULT ((0)) FOR [maxQty]
ALTER TABLE [dbo].[MISCHITEM] ADD  DEFAULT ((0)) FOR [basisQty]
ALTER TABLE [dbo].[MISCHITEM]  WITH CHECK ADD FOREIGN KEY([schId])
REFERENCES [dbo].[MISCHID] ([schId])
